import { useState } from "react";
import { Download, Search } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";

export default function ResearchRegistry() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<string>("all");
  const list = trpc.researchRegistry.list.useQuery({ query, ...(status === "all" ? {} : { status: status as "draft" | "preregistered" | "validated" | "rejected" | "inconclusive" }) });
  const summary = trpc.researchRegistry.summary.useQuery();
  return <DashboardLayout><main className="space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Research registry</h1><p className="text-sm text-muted-foreground">Owner-entered, research-only hypotheses. No registry status authorizes live trading.</p></div><section className="grid gap-4 md:grid-cols-4"><Card><CardHeader className="pb-2"><CardDescription>Total records</CardDescription><CardTitle>{summary.data?.total ?? 0}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Preregistered</CardDescription><CardTitle>{summary.data?.byStatus.preregistered ?? 0}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Validated</CardDescription><CardTitle>{summary.data?.byStatus.validated ?? 0}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Incomplete evidence</CardDescription><CardTitle>{summary.data?.incompleteEvidence ?? 0}</CardTitle></CardHeader></Card></section><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search hypotheses" /></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="draft">Draft</SelectItem><SelectItem value="preregistered">Preregistered</SelectItem><SelectItem value="validated">Validated</SelectItem><SelectItem value="rejected">Rejected</SelectItem><SelectItem value="inconclusive">Inconclusive</SelectItem></SelectContent></Select></div><Card><CardHeader><CardTitle>Hypotheses</CardTitle><CardDescription>Falsification criteria and protocol/result paths remain evidence references, not investment recommendations.</CardDescription></CardHeader><CardContent className="space-y-3">{list.data?.length ? list.data.map((record) => <div key={record.id} className="border-b pb-3 last:border-0"><div className="flex justify-between gap-4"><p className="font-medium">{record.title}</p><span className="text-xs text-muted-foreground">{record.status} · {record.sampleAdequacy}</span></div><p className="mt-1 text-sm text-muted-foreground">{record.hypothesis}</p><p className="mt-1 text-xs text-muted-foreground">Falsification: {record.falsificationCriteria}</p></div>) : <p className="text-sm text-muted-foreground">No research hypotheses match this view.</p>}</CardContent></Card></main></DashboardLayout>;
}
